Added mlflow page and updated module doc
olcf/olcf-user-docs pull request #466
Opened 2022-02-07 20:55 UTC by ketancmaheshwari

Added a page dedicated to MLflow and updated information about how to use swift and parsl modules.

2022-02-07 21:17 UTC, verolero86 requested changes
Thanks @ketancmaheshwari - I found just one edit but other than that it looks good to me.

2022-02-07 21:17 UTC, verolero86 commented on software/workflows/mlflow.rst
> +MLflow MLflow is an open source platform to manage the ML lifecycle, including
Remove duplicate "MLflow MLflow"

2022-02-07 21:25 UTC, ketancmaheshwari commented on software/workflows/mlflow.rst
> +MLflow MLflow is an open source platform to manage the ML lifecycle, including
Fixed. Thanks!

2022-02-08 22:59 UTC, ketancmaheshwari commented
Added a page for Fireworks.

2022-02-11 05:24 UTC, verolero86 approved these changes
Looks good to me! Thank you for updating MLflow section too 🙂

2022-02-11 05:24 UTC, merged